/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as EnquiryIndexRouteImport } from './routes/enquiry.index'
import { Route as EnquirySentRouteImport } from './routes/enquiry.sent'
import { Route as OfferOfferIdRouteImport } from './routes/offer.$offerId'
import { Route as AdminOffersIndexRouteImport } from './routes/admin.offers.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const EnquiryIndexRoute = EnquiryIndexRouteImport.update({
  id: '/enquiry/',
  path: '/enquiry/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquirySentRoute = EnquirySentRouteImport.update({
  id: '/enquiry/sent',
  path: '/enquiry/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferOfferIdRoute = OfferOfferIdRouteImport.update({
  id: '/offer/$offerId',
  path: '/offer/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOffersIndexRoute = AdminOffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/enquiry/sent': typeof EnquirySentRoute
  '/offer/$offerId': typeof OfferOfferIdRoute
  '/admin/': typeof AdminIndexRoute
  '/enquiry/': typeof EnquiryIndexRoute
  '/admin/offers/': typeof AdminOffersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/enquiry/sent': typeof EnquirySentRoute
  '/offer/$offerId': typeof OfferOfferIdRoute
  '/admin': typeof AdminIndexRoute
  '/enquiry': typeof EnquiryIndexRoute
  '/admin/offers': typeof AdminOffersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/enquiry/sent': typeof EnquirySentRoute
  '/offer/$offerId': typeof OfferOfferIdRoute
  '/admin/': typeof AdminIndexRoute
  '/enquiry/': typeof EnquiryIndexRoute
  '/admin/offers/': typeof AdminOffersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/enquiries'
    | '/enquiry/sent'
    | '/offer/$offerId'
    | '/admin/'
    | '/enquiry/'
    | '/admin/offers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/enquiries'
    | '/enquiry/sent'
    | '/offer/$offerId'
    | '/admin'
    | '/enquiry'
    | '/admin/offers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/enquiries'
    | '/enquiry/sent'
    | '/offer/$offerId'
    | '/admin/'
    | '/enquiry/'
    | '/admin/offers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EnquirySentRoute: typeof EnquirySentRoute
  OfferOfferIdRoute: typeof OfferOfferIdRoute
  EnquiryIndexRoute: typeof EnquiryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/enquiry/': {
      id: '/enquiry/'
      path: '/enquiry'
      fullPath: '/enquiry/'
      preLoaderRoute: typeof EnquiryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry/sent': {
      id: '/enquiry/sent'
      path: '/enquiry/sent'
      fullPath: '/enquiry/sent'
      preLoaderRoute: typeof EnquirySentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/$offerId': {
      id: '/offer/$offerId'
      path: '/offer/$offerId'
      fullPath: '/offer/$offerId'
      preLoaderRoute: typeof OfferOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/offers/': {
      id: '/admin/offers/'
      path: '/offers'
      fullPath: '/admin/offers/'
      preLoaderRoute: typeof AdminOffersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOffersIndexRoute: typeof AdminOffersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOffersIndexRoute: AdminOffersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EnquirySentRoute: EnquirySentRoute,
  OfferOfferIdRoute: OfferOfferIdRoute,
  EnquiryIndexRoute: EnquiryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
