/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as DifferencesRouteImport } from './routes/differences'
import { Route as OutletRouteImport } from './routes/outlet'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as EnquiryIndexRouteImport } from './routes/enquiry.index'
import { Route as EnquirySentRouteImport } from './routes/enquiry.sent'
import { Route as OfferTokenRouteImport } from './routes/offer.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCalculatorRouteImport } from './routes/_authenticated/admin.calculator'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin.enquiries'
import { Route as AuthenticatedAdminPriceListRouteImport } from './routes/_authenticated/admin.price-list'
import { Route as AuthenticatedAdminOffersIndexRouteImport } from './routes/_authenticated/admin.offers.index'
import { Route as AuthenticatedAdminOffersOfferIdRouteImport } from './routes/_authenticated/admin.offers.$offerId'
import { Route as AuthenticatedAdminOrdersIndexRouteImport } from './routes/_authenticated/admin.orders.index'
import { Route as AuthenticatedAdminOrdersOrderIdGlassRouteImport } from './routes/_authenticated/admin.orders.$orderId.glass'
import { Route as AuthenticatedAdminOrdersOrderIdProductionRouteImport } from './routes/_authenticated/admin.orders.$orderId.production'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const DifferencesRoute = DifferencesRouteImport.update({
  id: '/differences',
  path: '/differences',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletRoute = OutletRouteImport.update({
  id: '/outlet',
  path: '/outlet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EnquiryIndexRoute = EnquiryIndexRouteImport.update({
  id: '/enquiry/',
  path: '/enquiry/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquirySentRoute = EnquirySentRouteImport.update({
  id: '/enquiry/sent',
  path: '/enquiry/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferTokenRoute = OfferTokenRouteImport.update({
  id: '/offer/$token',
  path: '/offer/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCalculatorRoute =
  AuthenticatedAdminCalculatorRouteImport.update({
    id: '/calculator',
    path: '/calculator',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPriceListRoute =
  AuthenticatedAdminPriceListRouteImport.update({
    id: '/price-list',
    path: '/price-list',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOffersIndexRoute =
  AuthenticatedAdminOffersIndexRouteImport.update({
    id: '/offers/',
    path: '/offers/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOffersOfferIdRoute =
  AuthenticatedAdminOffersOfferIdRouteImport.update({
    id: '/offers/$offerId',
    path: '/offers/$offerId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersIndexRoute =
  AuthenticatedAdminOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersOrderIdGlassRoute =
  AuthenticatedAdminOrdersOrderIdGlassRouteImport.update({
    id: '/orders/$orderId/glass',
    path: '/orders/$orderId/glass',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersOrderIdProductionRoute =
  AuthenticatedAdminOrdersOrderIdProductionRouteImport.update({
    id: '/orders/$orderId/production',
    path: '/orders/$orderId/production',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/differences': typeof DifferencesRoute
  '/outlet': typeof OutletRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/enquiry/sent': typeof EnquirySentRoute
  '/offer/$token': typeof OfferTokenRoute
  '/enquiry/': typeof EnquiryIndexRoute
  '/admin/calculator': typeof AuthenticatedAdminCalculatorRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/price-list': typeof AuthenticatedAdminPriceListRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/offers/$offerId': typeof AuthenticatedAdminOffersOfferIdRoute
  '/admin/offers/': typeof AuthenticatedAdminOffersIndexRoute
  '/admin/orders/': typeof AuthenticatedAdminOrdersIndexRoute
  '/admin/orders/$orderId/glass': typeof AuthenticatedAdminOrdersOrderIdGlassRoute
  '/admin/orders/$orderId/production': typeof AuthenticatedAdminOrdersOrderIdProductionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/differences': typeof DifferencesRoute
  '/outlet': typeof OutletRoute
  '/enquiry/sent': typeof EnquirySentRoute
  '/offer/$token': typeof OfferTokenRoute
  '/enquiry': typeof EnquiryIndexRoute
  '/admin/calculator': typeof AuthenticatedAdminCalculatorRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/price-list': typeof AuthenticatedAdminPriceListRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/offers/$offerId': typeof AuthenticatedAdminOffersOfferIdRoute
  '/admin/offers': typeof AuthenticatedAdminOffersIndexRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersIndexRoute
  '/admin/orders/$orderId/glass': typeof AuthenticatedAdminOrdersOrderIdGlassRoute
  '/admin/orders/$orderId/production': typeof AuthenticatedAdminOrdersOrderIdProductionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/differences': typeof DifferencesRoute
  '/outlet': typeof OutletRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/enquiry/sent': typeof EnquirySentRoute
  '/offer/$token': typeof OfferTokenRoute
  '/enquiry/': typeof EnquiryIndexRoute
  '/_authenticated/admin/calculator': typeof AuthenticatedAdminCalculatorRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/price-list': typeof AuthenticatedAdminPriceListRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/offers/$offerId': typeof AuthenticatedAdminOffersOfferIdRoute
  '/_authenticated/admin/offers/': typeof AuthenticatedAdminOffersIndexRoute
  '/_authenticated/admin/orders/': typeof AuthenticatedAdminOrdersIndexRoute
  '/_authenticated/admin/orders/$orderId/glass': typeof AuthenticatedAdminOrdersOrderIdGlassRoute
  '/_authenticated/admin/orders/$orderId/production': typeof AuthenticatedAdminOrdersOrderIdProductionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/differences'
    | '/outlet'
    | '/admin'
    | '/enquiry/sent'
    | '/offer/$token'
    | '/enquiry/'
    | '/admin/calculator'
    | '/admin/enquiries'
    | '/admin/price-list'
    | '/admin/'
    | '/admin/offers/$offerId'
    | '/admin/offers/'
    | '/admin/orders/'
    | '/admin/orders/$orderId/glass'
    | '/admin/orders/$orderId/production'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/differences'
    | '/outlet'
    | '/enquiry/sent'
    | '/offer/$token'
    | '/enquiry'
    | '/admin/calculator'
    | '/admin/enquiries'
    | '/admin/price-list'
    | '/admin'
    | '/admin/offers/$offerId'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/orders/$orderId/glass'
    | '/admin/orders/$orderId/production'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cart'
    | '/differences'
    | '/outlet'
    | '/_authenticated/admin'
    | '/enquiry/sent'
    | '/offer/$token'
    | '/enquiry/'
    | '/_authenticated/admin/calculator'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/price-list'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/offers/$offerId'
    | '/_authenticated/admin/offers/'
    | '/_authenticated/admin/orders/'
    | '/_authenticated/admin/orders/$orderId/glass'
    | '/_authenticated/admin/orders/$orderId/production'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  DifferencesRoute: typeof DifferencesRoute
  OutletRoute: typeof OutletRoute
  EnquirySentRoute: typeof EnquirySentRoute
  OfferTokenRoute: typeof OfferTokenRoute
  EnquiryIndexRoute: typeof EnquiryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/differences': {
      id: '/differences'
      path: '/differences'
      fullPath: '/differences'
      preLoaderRoute: typeof DifferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlet': {
      id: '/outlet'
      path: '/outlet'
      fullPath: '/outlet'
      preLoaderRoute: typeof OutletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/enquiry/': {
      id: '/enquiry/'
      path: '/enquiry'
      fullPath: '/enquiry/'
      preLoaderRoute: typeof EnquiryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry/sent': {
      id: '/enquiry/sent'
      path: '/enquiry/sent'
      fullPath: '/enquiry/sent'
      preLoaderRoute: typeof EnquirySentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/$token': {
      id: '/offer/$token'
      path: '/offer/$token'
      fullPath: '/offer/$token'
      preLoaderRoute: typeof OfferTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calculator': {
      id: '/_authenticated/admin/calculator'
      path: '/calculator'
      fullPath: '/admin/calculator'
      preLoaderRoute: typeof AuthenticatedAdminCalculatorRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/price-list': {
      id: '/_authenticated/admin/price-list'
      path: '/price-list'
      fullPath: '/admin/price-list'
      preLoaderRoute: typeof AuthenticatedAdminPriceListRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/offers/': {
      id: '/_authenticated/admin/offers/'
      path: '/offers'
      fullPath: '/admin/offers/'
      preLoaderRoute: typeof AuthenticatedAdminOffersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/offers/$offerId': {
      id: '/_authenticated/admin/offers/$offerId'
      path: '/offers/$offerId'
      fullPath: '/admin/offers/$offerId'
      preLoaderRoute: typeof AuthenticatedAdminOffersOfferIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders/': {
      id: '/_authenticated/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AuthenticatedAdminOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders/$orderId/glass': {
      id: '/_authenticated/admin/orders/$orderId/glass'
      path: '/orders/$orderId/glass'
      fullPath: '/admin/orders/$orderId/glass'
      preLoaderRoute: typeof AuthenticatedAdminOrdersOrderIdGlassRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders/$orderId/production': {
      id: '/_authenticated/admin/orders/$orderId/production'
      path: '/orders/$orderId/production'
      fullPath: '/admin/orders/$orderId/production'
      preLoaderRoute: typeof AuthenticatedAdminOrdersOrderIdProductionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCalculatorRoute: typeof AuthenticatedAdminCalculatorRoute
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminPriceListRoute: typeof AuthenticatedAdminPriceListRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminOffersOfferIdRoute: typeof AuthenticatedAdminOffersOfferIdRoute
  AuthenticatedAdminOffersIndexRoute: typeof AuthenticatedAdminOffersIndexRoute
  AuthenticatedAdminOrdersIndexRoute: typeof AuthenticatedAdminOrdersIndexRoute
  AuthenticatedAdminOrdersOrderIdGlassRoute: typeof AuthenticatedAdminOrdersOrderIdGlassRoute
  AuthenticatedAdminOrdersOrderIdProductionRoute: typeof AuthenticatedAdminOrdersOrderIdProductionRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCalculatorRoute: AuthenticatedAdminCalculatorRoute,
  AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
  AuthenticatedAdminPriceListRoute: AuthenticatedAdminPriceListRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminOffersOfferIdRoute: AuthenticatedAdminOffersOfferIdRoute,
  AuthenticatedAdminOffersIndexRoute: AuthenticatedAdminOffersIndexRoute,
  AuthenticatedAdminOrdersIndexRoute: AuthenticatedAdminOrdersIndexRoute,
  AuthenticatedAdminOrdersOrderIdGlassRoute:
    AuthenticatedAdminOrdersOrderIdGlassRoute,
  AuthenticatedAdminOrdersOrderIdProductionRoute:
    AuthenticatedAdminOrdersOrderIdProductionRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  DifferencesRoute: DifferencesRoute,
  OutletRoute: OutletRoute,
  EnquirySentRoute: EnquirySentRoute,
  OfferTokenRoute: OfferTokenRoute,
  EnquiryIndexRoute: EnquiryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
